trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  serviceConnection : 'sc-azure'
  functionAppName: 'AzureFunctionInterets'
  packagePath: '$(Build.ArtifactStagingDirectory)/package.zip'

stages:
- stage: 'Build'
  displayName: 'Build the application'
  jobs: 
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/AzFunctionInterets.csproj'
      displayName: 'restaurer les packages'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        arguments: '--configuration $(buildConfiguration)'
        projects: '**/AzFunctionInterets.csproj'
      displayName: 'Génération de la solution'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '**/AzFunctionInterets.csproj'
        publishWebProjects: false
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true
      displayName: 'Génération du package de publication'
      
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
      displayName: 'Publication du package dans Azure DevOps'

- stage: 'Deploy'
  displayName: 'Deploy the web application'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    environment: Dev
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            displayName: 'Download artifact'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(Build.ArtifactStagingDirectory)'
          - task: AzureFunctionApp@1
            displayName: 'Azure Function Deploy'
            inputs:
              azureSubscription: $(serviceConnection)
              appType: functionApp
              appName: '$(functionAppName)'
              package: '$(Build.ArtifactStagingDirectory)/drop/package.zip'